---
title: "Homework 6"
subtitle: "Autumn 2023"
author: "WRITE YOUR NAME HERE"
date: "`r Sys.Date()`"
output: pdf_document
header-includes:
    - \usepackage{amsmath, amssymb}
    - \usepackage{setspace} 
---

\onehalfspacing

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

```


* * * 

### Instructions

- This homework is due in Gradescope on Wednesday Nov 15 by midnight PST. There is a 15 minute grace period and submissions made during this time will not be marked as late. Any work submitted past this period is considered late.  

- Please answer the following questions in the order in which they are posed. 

- Don't forget to (i) make a local copy this document for your work and to (ii) knit the document frequently to make sure there are no compilation errors. 

- When you are done, download the PDF file as instructed in section and submit it in Gradescope. 

* * *


### Exercises 


1. (Aphids) A large number of insects are expected to be attracted to a variety of rose plant. A commercial insecticide is advertised as being 99% effective. Suppose 2,000 aphids infest a rose garden where the insecticide has been applied and let the random variable $X$ denote the number of surviving aphids. 


a. What probability distribution might provide a reasonable model for the random variable $X$? Be sure to:

   - state the values for the parameters of the distribution 
   
   - state any assumption you need to make 

b. Using your model in part a, calculate $P(X < 10)$, the probability that fewer than 10 aphids survive. Be sure to do your calculation in a code chunk and then report the answer (rounded to three decimal places) in a complete sentence using inline code.


c. What other probability distribution might be computationally more convenient and would provide a good approximation for the probability in part b? Be sure to state the values for the parameters of the distribution.

d. Repeat the calculation in part b. using your model from part c. Be sure to do your calculation in a code chunk and then report the answer (rounded to three decimal places) in a complete sentence using inline code.

2. (Oysters) An oyster contains a pearl with probability $\pi$. You need a pearl for a tiara you are making, and keep opening oysters until you find one with a pearl. (poor oysters....)

a. Let the random variable $X$ denote the number of oysters you throw away before you find one with a pearl. Write the PMF of $X$. 

b. We want the probability that you have to throw away 3 or more oysters to be no larger than 0.05. To be specific, we want to find $\pi$ so that $P(X \geq 3)  \leq 0.05$. Find the minimum value of $\pi$ that ensures this probability. (In this part, you are solving this manually. Show your steps,  do any calculations in a code chunk and report the value of $\pi$ with inline code)

c. Repeat part b. using the `uniroot` function to obtain the value of $\pi$ by numerical methods. Be sure to show your code in a code chunk and print the result. (See problem 3 from `Problem6.Rmd`)

3. (Burnout) In a large factory building, where the fluorescent lights are kept on day and night, the lights burn out according to a Poisson process at a rate of $\lambda = 6$ per day. (Assume that lights are replaced as soon as they burn out for simplicity. Also a day refers to a 24 hour period.)

   For each part below, be sure to state the random variable and its distribution (if not already stated earlier), do calculations (if any) in a code chunk and report numerical answers in a complete sentence using inline code. (Rounding decimals to four digits is always a good idea)

a. Find the probability that there are more than two burnouts between noon and 1 PM tomorrow.

b. Find the probability that the next two burnouts will be at least 3 hours apart. 

c. On a certain day, you count the number of burnouts between 8 AM and 8 PM. Let the random variable $X$ denote the number of burnouts that occur during this 12 hour time period. How many burnouts should you expect? With what standard deviation? (Please give your answer in a complete sentence, don't just write two numbers)

d. On a certain day, you count the number of burnouts between 8 AM and 8 PM. Let the random variable $X$ denote the number of burnouts that occur during this 12 hour time period. What does Chebychev's inequality say about $P(1 < X < 5)$? Be sure to show your work.

e. Calculate the probability from part d. using the exact distribution of $X$. 
   
 
  
4. (Flooding river) A river floods every year. Suppose that the low-water mark is set at 1 and the high-water mark $X$ has CDF
\begin{align*}
	F(x) &= P(X \leq x) \\
	       &= \left\{ \begin{array}{cc} 
		               0 & x < 1 \\
		               1 - 1/x^2 & 1 \leq x < \infty. \end{array} \right.
\end{align*}

a.  Find a PDF, $f(x)$ for $X$. 

    Hint: see example 9.3 from Chapter 9.

b. If the low-water mark is set to 0 and we use a unit of measurement that is $\frac{1}{10}$ of that given previously, the high-water mark becomes $Y=10\:(X-1).$ Find $P(Y \geq 1)$. 

    Hint: $Y$ is just a transformation of $X$. Rewrite the event $Y \geq 1$ in terms of $X$ and find the probability of this event. 